brd = {
    "What subject does ADP 1-02 cover?": "Operational Terms and Military Symbols", 
    "What does ADP 4-0 cover?":"Sustainment",
    "What does the acronyms ADP,ADRP,NATO and JP stand for":"Army Doctorines Publications, Army Doctorines Referance Publications, North Atlantic Treaty Organizations, and Joint Publications",
    "Whats is Army Sustainment?":"Army sustainment is the provision of logistics, personnel services, and health services support necessary to maintain operations until successful mission completion.",
    "why are acronyms and abbreviations created?":"They allow Soldiers and marines to use shorter versions of the doctorine and military terms for ease of discussion in speaking and wrighting.",
    "What does APS stand for and what is its perpose?":"Army Preposition Stocks. The primary peroses of APS are to reduce the initial stratigic lift required to support a force projection Army and sustain the soldier until lines of communication are established",
    "How many catigories do military Symbols fall into and what are they?":"two-Framed and Unframed",
    "Define army logistics":"army logistics is the planning and exicution of the movement and support of forces.",
    "what does ADP 2-0 cover?":"intelligence",
    "How many Logic Map fundamentals are there and what are they?":"three-core competencies, Intelligence Process, and Intelligence Capabilities.",
    "What does PMESII-Pt stand for?":"Political, Military, Economincal, social, information, infrastructure, physical enviroment, and time.",
    "what does ADP 6-22 cover?":"army leadership",
    "What does ADP 3-37 cover?":"Protection",
    "How many Protection Principles are ther nad what are they?":"five-Comprehensive, Integrated, Layered, Redundant, and Enduring.",
    "What are the three army attributes?":"Character, Presence, and Intellect.",
    "What Publication/regulation/Doctorine covers 'The Army'?":"ADP 1",
    "What does 'ADP 1' Cover?":"The Army",
#    "What does 'ADP 1 Chapter 1' Cover?":"Why America needs an Army",
 #   "What does 'ADP 1 Chapter 2' Cover?":"Today's Army",
  #  "What does 'ADP 1 Chapter 3' Cover?":"Ready to fight, Prepared for the future, Determined to win",
    "What Publication/regulation/Doctorine covers 'Intelligence'?":"ADP 2-0",
    "What does 'ADP 2-0' Cover?":"Intelligence",
#    "What does 'ADP 2-0 Chapter 1' Cover?":"Operations and Intelligence",
 #   "What does 'ADP 2-0 Chapter 2' Cover?":"Intelligence Support",
  #  "What does 'ADP 2-0 Chapter 3' Cover?":"The Intelligence Process",
   # "What does 'ADP 2-0 Chapter 4' Cover?":"Army Intelligence Capabilities",
    #"What does 'ADP 2-0 Chapter 5' Cover?":"Fighting for Intelligence",
    "What Publication/regulation/Doctorine covers 'Operations'?":"ADP 3-0",
    "What does 'ADP 3-0' Cover?":"Operations",
#    "What does 'ADP 3-0 Chapter 1' Cover?":"Military Operations",
 #   "What does 'ADP 3-0 Chapter 2' Cover?":"Operational Art",
  #  "What does 'ADP 3-0 Chapter 3' Cover?":"The Army's Operational Concept",
   # "What does 'ADP 3-0 Chapter 4' Cover?":"Operations Structure",
    #"What does 'ADP 3-0 Chapter 5' Cover?":"Combat Power",
    "What Publication/regulation/Doctorine covers 'Army Special Operations'?":"ADP 3-05",
    "What does 'ADP 3-05' Cover?":"Army Special operations",
#    "What does 'ADP 3-05 Chapter 1' Cover?":"Overview of Army Special Operations",
 #   "What does 'ADP 3-05 Chapter 2' Cover?":"Core Activities",
  #  "What does 'ADP 3-05 Chapter 3' Cover?":"Command and Control Structures",
   # "What does 'ADP 3-05 Chapter 4' Cover?":"Fires",
    #"What does 'ADP 3-05 Chapter 5' Cover?":"Intellignce",
#    "What does 'ADP 3-05 Chapter 6' Cover?":"Sustainment",
 #   "What does 'ADP 3-05 Chapter 7' Cover?":"Protection",
  #  "What does 'ADP 3-05 Chapter 8' Cover?":"Employment",
    "What Publication/regulation/Doctorine covers 'Defense Support of Civil Authorities'?":"ADP 3-28",
    "What does 'ADP 3-28' Cover?":"Defense Support of Civil Authorities",
#    "What does 'ADP 3-28 Chapter 1' Cover?":"Framework",
 #   "What does 'ADP 3-28 Chapter 2' Cover?":"Army Support",
  #  "What does 'ADP 3-28 Chapter 3' Cover?":"Organization for Army Support",
   # "What does 'ADP 3-28 Chapter 4' Cover?":"Response",
    "What Publication/regulation/Doctorine covers 'Protection'?":"ADP 3-37",
    "What does 'ADP 3-37' Cover?":"Protection",
#    "What does 'ADP 3-37 Chapter 1' Cover?":"Protection Framework",
 #   "What does 'ADP 3-37 Chapter 2' Cover?":"Protection Tasks",
  #  "What does 'ADP 3-37 Chapter 3' Cover?":"Protection Planning",
   # "What does 'ADP 3-37 Chapter 4' Cover?":"Protection Preparation",
    #"What does 'ADP 3-37 Chapter 5' Cover?":"Protection Execution",
#    "What does 'ADP 3-37 Chapter 6' Cover?":"Protection Assesment",
    "What Publication/regulation/Doctorine covers 'Offense and Defense'?":"ADP 3-90",
    "What does 'ADP 3-90' Cover?":"Offense and Defense",
#    "What does 'ADP 3-90 Chapter 1' Cover?":"Tactical Fundamentals",
 #   "What does 'ADP 3-90 Chapter 2' Cover?":"Common Tactical Concepts and Echelons",
  #  "What does 'ADP 3-90 Chapter 3' Cover?":"The Offense",
   # "What does 'ADP 3-90 Chapter 4' Cover?":"The Defense",
    #"What does 'ADP 3-90 Chapter 5' Cover?":"Enabling Opertaions",
    "What Publication/regulation/Doctorine covers 'Sustainment'?":"ADP 4-0",
    "What does 'ADP 4-0' Cover?":"Sustainment",
#    "What does 'ADP 4-0 Chapter 1' Cover?":"Fundamentals of Sustainment",
 #   "What does 'ADP 4-0 Chapter 2' Cover?":"Sustainment of Unified Action",
  #  "What does 'ADP 4-0 Chapter 3' Cover?":"Sustainment of Unified Land Operations",
    "What Publication/regulation/Doctorine covers 'The Operations Proccess'?":"ADP 5-0",
    "What does 'ADP 5-0' Cover?":"The Operations Proccess",
#    "What does 'ADP 5-0 Chapter 1' Cover?":"Fundamentals of the Operations Process",
 #   "What does 'ADP 5-0 Chapter 2' Cover?":"Planning",
  #  "What does 'ADP 5-0 Chapter 3' Cover?":"Preparations",
   # "What does 'ADP 5-0 Chapter 4' Cover?":"Execution",
    #"What does 'ADP 5-0 Chapter 5' Cover?":"Assessment",
    "What Publication/regulation/Doctorine covers 'Army Leadership and the Profession'?":"ADP 6-22",
    "What does 'ADP 6-22' Cover?":"Army Leadership and the Profession",
#    "What does 'ADP 6-22 Chapter 1' Cover?":"The Army Profession, Ethic, and Leadership",
 #   "What does 'ADP 6-22 Chapter 2' Cover?":"Character",
  #  "What does 'ADP 6-22 Chapter 3' Cover?":"Presence",
   # "What does 'ADP 6-22 Chapter 4' Cover?":"Intellect",
    #"What does 'ADP 6-22 Chapter 5' Cover?":"Leads",
#    "What does 'ADP 6-22 Chapter 6' Cover?":"Develops",
 #   "What does 'ADP 6-22 Chapter 7' Cover?":"Achieves",
  #  "What does 'ADP 6-22 Chapter 8' Cover?":"Leadership in Practice",
   # "What does 'ADP 6-22 Chapter 9' Cover?":"Organizational Leadership",
    #"What does 'ADP 6-22 Chapter 10' Cover?":"Strategic Leadership",
    "What Publication/regulation/Doctorine covers 'Leaves and Passes'?":"AR 600-8-10",
    "What does 'AR 600-8-10' Cover?":"Leaves and Passes",
    #"What does 'AR 600-8-10 Chapter 1' Cover?":"Introduction",
    #"What does 'AR 600-8-10 Chapter 2' Cover?":"Policy for Leave",
    #"What does 'AR 600-8-10 Chapter 3' Cover?":"Special Leave Accrual",
    #"What does 'AR 600-8-10 Chapter 4' Cover?":"Chargable Leave",
    #"What does 'AR 600-8-10 Chapter 5' Cover?":"Non-Chargable Leave and Absences",
    #"What does 'AR 600-8-10 Chapter 6' Cover?":"Chargable and Non-Chargable Leave Combinations",
    #"What does 'AR 600-8-10 Chapter 7' Cover?":"Pass",
    #"What does 'AR 600-8-10 Chapter 8' Cover?":"Leave Together with Permanent Change of Station",
    #"What does 'AR 600-8-10 Chapter 9' Cover?":"Christmas-New Year Holiday Period for Personnel in Training",
    #"What does 'AR 600-8-10 Chapter 10' Cover?":"Changes in Leave",
    #"What does 'AR 600-8-10 Chapter 11' Cover?":"Leave Management",
    #"What does 'AR 600-8-10 Chapter 12' Cover?":"Processing Procedures",
    "What Publication/regulation/Doctorine covers 'Army Command Policy'?":"AR 600-20",
    "What does 'AR 600-20' Cover?":"Army Command Policy",
    #"What does 'AR 600-20 Chapter 1' Cover?":"Introduction",
    #"What does 'AR 600-20 Chapter 2' Cover?":"Command Policies",
    #"What does 'AR 600-20 Chapter 3' Cover?":"Ready and resilient",
    #"What does 'AR 600-20 Chapter 4' Cover?":"Military Discipline and Conduct",
    #"What does 'AR 600-20 Chapter 5' Cover?":"Other Responsibilities of Command",
    "What does 'AR 600-20 Chapter 6' Cover?":"Military Equal Opportunity Policy and Program",
    "What does 'AR 600-20 Chapter 7' Cover?":"Sexual Harassment/Assault Response and Prevention Program",
    "What Publication/regulation/Doctorine covers 'Wear and Appearance of Army Uniforms and Insignia'?":"",
    "What does 'AR 670-1' Cover?":"Wear and Appearance of Army Uniforms and Insignia",
    #"What does 'AR 670-1 Chapter 1' Cover?":"Introduction",
    #"What does 'AR 670-1 Chapter 2' Cover?":"Responsibilities",
    #"What does 'AR 670-1 Chapter 3' Cover?":"Appearance and Grooming Policies",
    #"What does 'AR 670-1 Chapter 4' Cover?":"Combat Uniform",
    #"What does 'AR 670-1 Chapter 5' Cover?":"Maternity Work Uniform",
    #"What does 'AR 670-1 Chapter 6' Cover?":"Aircrew Uniform",
    #"What does 'AR 670-1 Chapter 7' Cover?":"Garrison Culinary Uniform-Male",
    #"What does 'AR 670-1 Chapter 8' Cover?":"Garrison Culinary Uniform-Female",
    #"What does 'AR 670-1 Chapter 9' Cover?":"Combat Vehicle Crewman Uniform",
    #"What does 'AR 670-1 Chapter 10' Cover?":"Physical Fitness Uniform",
    #"What does 'AR 670-1 Chapter 11' Cover?":"Army Service Uniform-Male",
    #"What does 'AR 670-1 Chapter 12' Cover?":"Army Service Uniform-Female",
    #"What does 'AR 670-1 Chapter 13' Cover?":"Army Service Uniform-Maternity",
    #"What does 'AR 670-1 Chapter 14' Cover?":"Army Green Service Uniform",
    #"What does 'AR 670-1 Chapter 15' Cover?":"The Army Green Service Uniform-Maternity",
    #"What does 'AR 670-1 Chapter 16' Cover?":"Blue Mess Uniforms-Male",
    #"What does 'AR 670-1 Chapter 17' Cover?":"Blue Mess Uniforms-Female",
    #"What does 'AR 670-1 Chapter 18' Cover?":"White Mess Uniforms-Male",
    #"What does 'AR 670-1 Chapter 19' Cover?":"White Mess Uniforms-Female",
    #"What does 'AR 670-1 Chapter 20' Cover?":"Uniform Accessories",
    #"What does 'AR 670-1 Chapter 21' Cover?":"Wear of Insignia and Accoutrements",
    #"What does 'AR 670-1 Chapter 22' Cover?":"Wear of Decorations, Service Medals, Badges, Unit Awards, and Appurtenances",
    #"What does 'AR 670-1 Chapter 23' Cover?":"Wear of the Army Uniform by Reserve, Retired, Separated, and Civilian Personnel",
    "What Publication/regulation/Doctorine covers 'The Counseling Process'?":"ATP 6-22.1",
    "What does 'ATP 6-22.1' Cover?":"The Counseling Process",
    #"What does 'ATP 6-22.1 Chapter 1' Cover?":"COUNSELING",
    #What does 'ATP 6-22.1 Chapter 2' Cover?":"COUSELING FUNDAMENTALS",
    "What Publication/regulation/Doctorine covers 'Army Team Building'?":"ATP 6-22.6",
    "What does 'ATP 6-22.6' Cover?":"Army Team Building",
    #"What does 'ATP 6-22.6 Chapter 1' Cover?":"FUNDAMENTALS OF TEAM BUILDING",
    #"What does 'ATP 6-22.6 Chapter 2' Cover?":"FORMATION STAGE",
    #"What does 'ATP 6-22.6 Chapter 3' Cover?":"ENRICHMENT STAGE",
    #"What does 'ATP 6-22.6 Chapter 4' Cover?":"SUSTAINMENT STAGE",
    "What Publication/regulation/Doctorine covers 'Holistic Health and Fitness'?":"FM 7-22",
    "What does 'FM 7-22' Cover?":"Holistic Health and Fitness",
    #"What does 'FM 7-22 Chapter 1' Cover?":"PRINCIPLES AND ELEMENTS",
    #"What does 'FM 7-22 Chapter 2' Cover?":"PHASES",
    #"What does 'FM 7-22 Chapter 3' Cover?":"DOMAINS",
   # "What does 'FM 7-22 Chapter 4' Cover?":"PHYSIOLOGY",
    #"What does 'FM 7-22 Chapter 5' Cover?":"PERIODIZATION",
   # "What does 'FM 7-22 Chapter 6' Cover?":"PROGRAM DESIGN",
   # "What does 'FM 7-22 Chapter 7' Cover?":"PHYSICAL READINESS",
   # "What does 'FM 7-22 Chapter 8' Cover?":"NUTRITIONAL READINESS",
   # "What does 'FM 7-22 Chapter 9' Cover?":"MENTAL READINESS",
   # "What does 'FM 7-22 Chapter 10' Cover?":"SPIRITUAL READINESS",
   # "What does 'FM 7-22 Chapter 11' Cover?":"SLEEP READINESS",
    #"What does 'FM 7-22 Chapter 12' Cover?":"SPECIAL CONDITIONING",
   # "What does 'FM 7-22 Chapter 13' Cover?":"HOLISTIC HEALTH AND FITNESS COACHING",
    #"What does 'FM 7-22 Chapter 14' Cover?":"HOLISTIC HEALTH AND FITNESS SCHEDULES",
    "What Publication/regulation/Doctorine covers 'Warrior Skills Level 1'?":"STP 21-1-SMCT",
    "What does 'STP 21-1-SMCT' Cover?":"Warrior Skills Level 1",
    "What Publication/regulation/Doctorine covers 'Warrior Skills Level 2,3, and 4'?":"STP 21-24-SMCT",
    "What does 'STP 21-24-SMCT' Cover?":"Warrior Skills Level 2,3, and 4",
    "What Publication/regulation/Doctorine covers 'Drill and Ceremonies'?":"TC 3-21.5",
#    "What does 'TC 3-21.5' Cover?":"Drill and Ceremonies",
 #   "What does 'TC 3-21.5 Chapter 1' Cover?":"INTRODUCTION",
  #  "What does 'TC 3-21.5 Chapter 2' Cover?":"DRILL INSTRUCTIONS",
   # "What does 'TC 3-21.5 Chapter 3' Cover?":"COMMANDS AND THE COMMAND VOICE",
    #"What does 'TC 3-21.5 Chapter 4' Cover?":"INDIVIDUAL DRILL",
#    "What does 'TC 3-21.5 Chapter 5' Cover?":"INDIVIDUAL DRILL WITH WEAPONS",
 #  "What does 'TC 3-21.5 Chapter 7' Cover?":"PLATOON DRILL",
  #  "What does 'TC 3-21.5 Chapter 8' Cover?":"COMPANY DRILL",
   # "What does 'TC 3-21.5 Chapter 9' Cover?":"BATTALION AND BRIGADE DRILL",
    #"What does 'TC 3-21.5 Chapter 10' Cover?":"REVIEWS",
#    "What does 'TC 3-21.5 Chapter 11' Cover?":"PARADES",
 #   "What does 'TC 3-21.5 Chapter 12' Cover?":"HONOR GUARDS",
  #  "What does 'TC 3-21.5 Chapter 13' Cover?":"RETREATS AND REVEILLES",
   # "What does 'TC 3-21.5 Chapter 14' Cover?":"FUNERALS",
    #"What does 'TC 3-21.5 Chapter 15' Cover?":"COLORS",
#    "What does 'TC 3-21.5 Chapter 16' Cover?":"SALUTE BATTERY",
  #  "What does 'TC 3-21.5 Chapter 17' Cover?":"CIVILIAN PARTICIPATION IN MILITARY CEREMONIES",
    "What does TIMS Mean?":"This is my Squad",
    "what is this is my squad":"a leadership philosophy and communication program to cultivate a culture of care, pride and ownership in small units across the total army",
    #"TIMS desired effect for junior NCOs":"empower to care for soldiers and solve problems inform as their authority as NCOs",
    #"TIMS desired effect for senior NCOs":"educate to identify powerful team characteristics empower to replicate excellence",
    #"TIMS desired effect for officers":"build trust in junior NCOs, maintain trust in senior NCOs",
    #"what are the different channels of TIMS":"nco support channel,face-to - face, external media, owned media, outreach",
    #"what are the different desired effects classes of TIMS":"junior NCOS, seniorNCOs, officers, lower enlisted, american people, families",
    "What does ASAP stand for?":"Army Substance Abuse Program",
    "What is the mission of ASAP?":"The ASAP mission is to strengthen the overall fitness and effectiveness of the Army’s total workforce and to enhance the combat readiness of its Soldiers.",
    "What army Regulation covers ASAP?":"AR 600-85",
    "What does AR 600-85 cover?":"Army Substance Abuse Program (ASAP)",
    "Will Soldiers who are command referred to ASAP be flagged?":"Yes, IAW AR600-8-2 (Suspension of Favorable Personnel Action (flags)).",
    "What Does ACS stand for?":"Army Community Service",
    "What Army regulation covers ACS?":"AR 608-1",
    "What regulation covers Army Learning Centers?":"AR 621-6",
    "What regulation covers the ACES?":"AR 621-5",
    "What does TABE stand for?":"Test of Adult Basic Education",
    "What does DANTES stand for?":"Defense Activity for Non-Traditional Education Support",
    "What does SOC stand for?":"Service members Opportunity Colleges",
    "What does SOCAD stand for?":"Service members Opportunity College Army Degrees",
    "AER closely coordinates with what other organization?":"American Red Cross",
    "What does AER stand for?":"Army Emergency Relief",
    "What is the Army Regulation that covers AER?":"AR 930-4",
    "What regulation outlines the rights of crime victims?":"AR 27-10",
    "What is an EOR?":"EqualOpportunity Representative",
    "What rank should an EOR normally be?":"SGT (P)through 1LT",
    "What Army Regulation covers the EO program?":"AR 600-20 chapter 6",
    "What Army Regulation covers the SHARP program?":"AR 600-20 chapter 7",
    "What Army Regulation covers the Army Family Action Plan?":"AR 608-47",
    "What does AFAP Stand for?":"Army Family Action Plan",
    "What are the PT Preperation drills":"Bend and reach / Rear Lunge / High Jumper / Rower / Squat Bender / Windmill / Forward Lunge / Prone Row / Bent-Leg Body Twist / Push up",
    "What excersizes are in 4 for the core?":"Bent-Leg raise / Side Bridge / back Bridge / Quadraplex",
    "what excersizes arinthe hip stability drill?":"Lateral Leg raise / Medial leg raise / lateral bent leg raise / single leg tuck / single leg over",
    "What is int CD1 (Conditioning drill 1)":"bend and reach / rear lunge / high jumper / rower / squat bender / windmill / forward lunge / prone row / bent leg body twist / push up",
    "what is in the stretch drill":"overhead arm pull / rear lunge / extend and flex / thigh stretch / single leg over",
    "what is cover in conditioning drill 2 (CD2)?":"Push up / sit up / Pull up",
    "what is cover in conditioning drill 3 (CD3)":"The Power Jump / The V-up / mountain climber / leg tuck and twist / single leg push up",
    "What is your first General Order":"I will guard everything within the limits of my post and quit my post only when properly relieved.",
    "What is your second General Order":"i will obay my special orders and perform all my duties in a military manner.",
    "What is your third General Order":"i will report violations of my special orders, emergencies, and anything not covered in my in my instructions to the commander of the relief.",
    "What is the 1st stanza for the NCO Creed?":"No one is more proffesional than I. I am a noncommissioned officer, a leader of soldiers. As a noncommissioned officer \nI realize that I am a member of a time honored corps known as the backbone of the army\nI am proud of the corps of noncommissioned officers and will at all times conduct myself so as to bring credit\nupon the Corps, the military service and my country reguardless of the situation in which i find myself. \nI will not use my grade or postion to attain pleasure, profit, or personal safety.",
    "What is the 2nd stanza for the NCO Creed?":"Competence is my watchword. My two basic responsibilities will always be uppermost in my mind-- \naccomplishment of my mission and the welfare of my Soldiers.\nI will strive to remain technically and tactically proficient. I am aware of my role as a noncommissioned officer. I will fulfill my responsibilities inherent in that role. \nAll Soldiers are entitled to outstanding leadership; I will provide that leadership. I know my Soldiers and I will always place their needs above my own.\nI will communicate consistently with my Soldiers and never leave them uninformed. I will be fair and impartial when recommending both rewards and punishment.",
    "What is the 3rd stanza for the NCO Creed?":"Officers of my unit will have maximum time to accomplish their duties; they will not have to accomplish mine. \nI will earn their respect and confidence as well as that of my Soldiers. I will be loyal to those with whom I serve; seniors, peers, and subordinates alike.\nI will exercise initiative by taking appropriate action in the absence of orders. \nI will not compromise my integrity, nor my moral courage. I will not forget, nor will I allow my comrades to forget that we are \nprofessionals, noncommissioned officers, leaders!",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    
}